homepage:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Default:index }

hello:
    resource: @HelloBundle/Resources/config/routing.yml

timesheet:
    resource: @TimesheetBundle/Resources/config/routing.yml
